// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package main

import (
	"github.com/uma-universal-money-address/uma-auth-api/codegen/go/umaauth"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	UmaAuthAPIService := umaauth.NewUmaAuthAPIService()
	UmaAuthAPIController := umaauth.NewUmaAuthAPIController(UmaAuthAPIService)

	router := umaauth.NewRouter(UmaAuthAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
