templateDir: codegen-config/go/templates
additionalProperties:
  sourceFolder: umaauth
  onlyInterfaces: true
gitUserId: uma-universal-money-address
gitRepoId: uma-auth-api/codegen/go
packageName: umaauth
files:
  LICENSE: {}
  go.mod.mustache:
    destinationFilename: go.mod
