// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type LookupUserResponse struct {

	// The currencies the receiver accepts in order of preference.
	Currencies []CurrencyPreference `json:"currencies,omitempty"`
}

// AssertLookupUserResponseRequired checks if the required fields are not zero-ed
func AssertLookupUserResponseRequired(obj LookupUserResponse) error {
	for _, el := range obj.Currencies {
		if err := AssertCurrencyPreferenceRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertLookupUserResponseConstraints checks if the values respects the defined constraints
func AssertLookupUserResponseConstraints(obj LookupUserResponse) error {
	for _, el := range obj.Currencies {
		if err := AssertCurrencyPreferenceConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
