// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type GetBalanceRequest struct {

	// The currency code of the balance. Assumed to be in msats if not provided.
	CurrencyCode *string `json:"currency_code,omitempty"`
}

// AssertGetBalanceRequestRequired checks if the required fields are not zero-ed
func AssertGetBalanceRequestRequired(obj GetBalanceRequest) error {
	return nil
}

// AssertGetBalanceRequestConstraints checks if the values respects the defined constraints
func AssertGetBalanceRequestConstraints(obj GetBalanceRequest) error {
	return nil
}
