// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth


import (
	"time"
)



type Quote struct {

	// The currency code of the sender's balance.
	SendingCurrencyCode string `json:"sending_currency_code,omitempty"`

	// The currency code of the receiver's balance.
	ReceivingCurrencyCode string `json:"receiving_currency_code,omitempty"`

	// The payment hash of the quote. Used as an identifier to execute the quote.
	PaymentHash string `json:"payment_hash,omitempty"`

	// The time the quote expires.
	ExpiresAt time.Time `json:"expires_at,omitempty"`

	// Number of sending currency units per receiving currency unit.
	Multiplier float32 `json:"multiplier,omitempty"`

	// The fees associated with the quote in the smallest unit of the sending currency (eg. cents).
	Fees float32 `json:"fees,omitempty"`

	// The total amount that will be sent in the smallest unit of the sending currency (eg. cents).
	TotalSendingAmount float32 `json:"total_sending_amount,omitempty"`

	// The total amount that will be received in the smallest unit of the receiving currency (eg. cents).
	TotalReceivingAmount float32 `json:"total_receiving_amount,omitempty"`

	// The time the quote was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// AssertQuoteRequired checks if the required fields are not zero-ed
func AssertQuoteRequired(obj Quote) error {
	return nil
}

// AssertQuoteConstraints checks if the values respects the defined constraints
func AssertQuoteConstraints(obj Quote) error {
	return nil
}
