from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth import util


class BudgetEstimateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, estimated_budget_currency_amount=None):  # noqa: E501
        """BudgetEstimateResponse - a model defined in OpenAPI

        :param estimated_budget_currency_amount: The estimated_budget_currency_amount of this BudgetEstimateResponse.  # noqa: E501
        :type estimated_budget_currency_amount: int
        """
        self.openapi_types = {
            'estimated_budget_currency_amount': int
        }

        self.attribute_map = {
            'estimated_budget_currency_amount': 'estimated_budget_currency_amount'
        }

        self._estimated_budget_currency_amount = estimated_budget_currency_amount

    @classmethod
    def from_dict(cls, dikt) -> 'BudgetEstimateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BudgetEstimateResponse of this BudgetEstimateResponse.  # noqa: E501
        :rtype: BudgetEstimateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def estimated_budget_currency_amount(self) -> int:
        """Gets the estimated_budget_currency_amount of this BudgetEstimateResponse.

        The estimated cost of the payment in the smallest unit of  `budget_currency_code`. This amount will be used to calculate  the amount to hold from the budget for this connection while  the payment is in-flight.   # noqa: E501

        :return: The estimated_budget_currency_amount of this BudgetEstimateResponse.
        :rtype: int
        """
        return self._estimated_budget_currency_amount

    @estimated_budget_currency_amount.setter
    def estimated_budget_currency_amount(self, estimated_budget_currency_amount: int):
        """Sets the estimated_budget_currency_amount of this BudgetEstimateResponse.

        The estimated cost of the payment in the smallest unit of  `budget_currency_code`. This amount will be used to calculate  the amount to hold from the budget for this connection while  the payment is in-flight.   # noqa: E501

        :param estimated_budget_currency_amount: The estimated_budget_currency_amount of this BudgetEstimateResponse.
        :type estimated_budget_currency_amount: int
        """
        if estimated_budget_currency_amount is None:
            raise ValueError("Invalid value for `estimated_budget_currency_amount`, must not be `None`")  # noqa: E501
        if estimated_budget_currency_amount is not None and estimated_budget_currency_amount <= 0:  # noqa: E501
            raise ValueError("Invalid value for `estimated_budget_currency_amount`, must be a value greater than `0`")  # noqa: E501

        self._estimated_budget_currency_amount = estimated_budget_currency_amount
