from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth import util


class ErrorCode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RATE_LIMITED = 'RATE_LIMITED'
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
    PAYMENT_FAILED = 'PAYMENT_FAILED'
    NOT_FOUND = 'NOT_FOUND'
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED'
    RESTRICTED = 'RESTRICTED'
    UNAUTHORIZED = 'UNAUTHORIZED'
    INTERNAL = 'INTERNAL'
    OTHER = 'OTHER'
    def __init__(self):  # noqa: E501
        """ErrorCode - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorCode of this ErrorCode.  # noqa: E501
        :rtype: ErrorCode
        """
        return util.deserialize_model(dikt, cls)
