from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth import util


class ExecuteQuoteRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, budget_currency_code=None):  # noqa: E501
        """ExecuteQuoteRequest - a model defined in OpenAPI

        :param budget_currency_code: The budget_currency_code of this ExecuteQuoteRequest.  # noqa: E501
        :type budget_currency_code: str
        """
        self.openapi_types = {
            'budget_currency_code': str
        }

        self.attribute_map = {
            'budget_currency_code': 'budget_currency_code'
        }

        self._budget_currency_code = budget_currency_code

    @classmethod
    def from_dict(cls, dikt) -> 'ExecuteQuoteRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExecuteQuoteRequest of this ExecuteQuoteRequest.  # noqa: E501
        :rtype: ExecuteQuoteRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def budget_currency_code(self) -> str:
        """Gets the budget_currency_code of this ExecuteQuoteRequest.

        The code of the currency the sender used to set budget.  Optional if it is the same as `sending_currency_code`.  # noqa: E501

        :return: The budget_currency_code of this ExecuteQuoteRequest.
        :rtype: str
        """
        return self._budget_currency_code

    @budget_currency_code.setter
    def budget_currency_code(self, budget_currency_code: str):
        """Sets the budget_currency_code of this ExecuteQuoteRequest.

        The code of the currency the sender used to set budget.  Optional if it is the same as `sending_currency_code`.  # noqa: E501

        :param budget_currency_code: The budget_currency_code of this ExecuteQuoteRequest.
        :type budget_currency_code: str
        """

        self._budget_currency_code = budget_currency_code
