from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth import util


class GetBalanceRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, currency_code=None):  # noqa: E501
        """GetBalanceRequest - a model defined in OpenAPI

        :param currency_code: The currency_code of this GetBalanceRequest.  # noqa: E501
        :type currency_code: str
        """
        self.openapi_types = {
            'currency_code': str
        }

        self.attribute_map = {
            'currency_code': 'currency_code'
        }

        self._currency_code = currency_code

    @classmethod
    def from_dict(cls, dikt) -> 'GetBalanceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetBalanceRequest of this GetBalanceRequest.  # noqa: E501
        :rtype: GetBalanceRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def currency_code(self) -> str:
        """Gets the currency_code of this GetBalanceRequest.

        The currency code of the balance. Assumed to be in msats if not provided.  # noqa: E501

        :return: The currency_code of this GetBalanceRequest.
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code: str):
        """Sets the currency_code of this GetBalanceRequest.

        The currency code of the balance. Assumed to be in msats if not provided.  # noqa: E501

        :param currency_code: The currency_code of this GetBalanceRequest.
        :type currency_code: str
        """

        self._currency_code = currency_code
