from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth.models.currency import Currency
from uma_auth import util

from uma_auth.models.currency import Currency  # noqa: E501

class GetBalanceResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, balance=None, currency=None):  # noqa: E501
        """GetBalanceResponse - a model defined in OpenAPI

        :param balance: The balance of this GetBalanceResponse.  # noqa: E501
        :type balance: float
        :param currency: The currency of this GetBalanceResponse.  # noqa: E501
        :type currency: Currency
        """
        self.openapi_types = {
            'balance': float,
            'currency': Currency
        }

        self.attribute_map = {
            'balance': 'balance',
            'currency': 'currency'
        }

        self._balance = balance
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'GetBalanceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetBalanceResponse of this GetBalanceResponse.  # noqa: E501
        :rtype: GetBalanceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> float:
        """Gets the balance of this GetBalanceResponse.

        The balance of the user's wallet.  # noqa: E501

        :return: The balance of this GetBalanceResponse.
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance: float):
        """Sets the balance of this GetBalanceResponse.

        The balance of the user's wallet.  # noqa: E501

        :param balance: The balance of this GetBalanceResponse.
        :type balance: float
        """
        if balance is None:
            raise ValueError("Invalid value for `balance`, must not be `None`")  # noqa: E501
        if balance is not None and balance < 0:  # noqa: E501
            raise ValueError("Invalid value for `balance`, must be a value greater than or equal to `0`")  # noqa: E501

        self._balance = balance

    @property
    def currency(self) -> Currency:
        """Gets the currency of this GetBalanceResponse.


        :return: The currency of this GetBalanceResponse.
        :rtype: Currency
        """
        return self._currency

    @currency.setter
    def currency(self, currency: Currency):
        """Sets the currency of this GetBalanceResponse.


        :param currency: The currency of this GetBalanceResponse.
        :type currency: Currency
        """

        self._currency = currency
