from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth import util


class LockedCurrencySide(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SENDING = 'sending'
    RECEIVING = 'receiving'
    def __init__(self):  # noqa: E501
        """LockedCurrencySide - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'LockedCurrencySide':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LockedCurrencySide of this LockedCurrencySide.  # noqa: E501
        :rtype: LockedCurrencySide
        """
        return util.deserialize_model(dikt, cls)
