from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uma_auth.models.base_model import Model
from uma_auth.models.currency import Currency
from uma_auth import util

from uma_auth.models.currency import Currency  # noqa: E501

class TransactionFx(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, receiving_currency=None, sending_currency=None, total_receiving_amount=None, total_sending_amount=None, multiplier=None, fees=None):  # noqa: E501
        """TransactionFx - a model defined in OpenAPI

        :param receiving_currency: The receiving_currency of this TransactionFx.  # noqa: E501
        :type receiving_currency: Currency
        :param sending_currency: The sending_currency of this TransactionFx.  # noqa: E501
        :type sending_currency: Currency
        :param total_receiving_amount: The total_receiving_amount of this TransactionFx.  # noqa: E501
        :type total_receiving_amount: int
        :param total_sending_amount: The total_sending_amount of this TransactionFx.  # noqa: E501
        :type total_sending_amount: int
        :param multiplier: The multiplier of this TransactionFx.  # noqa: E501
        :type multiplier: float
        :param fees: The fees of this TransactionFx.  # noqa: E501
        :type fees: int
        """
        self.openapi_types = {
            'receiving_currency': Currency,
            'sending_currency': Currency,
            'total_receiving_amount': int,
            'total_sending_amount': int,
            'multiplier': float,
            'fees': int
        }

        self.attribute_map = {
            'receiving_currency': 'receiving_currency',
            'sending_currency': 'sending_currency',
            'total_receiving_amount': 'total_receiving_amount',
            'total_sending_amount': 'total_sending_amount',
            'multiplier': 'multiplier',
            'fees': 'fees'
        }

        self._receiving_currency = receiving_currency
        self._sending_currency = sending_currency
        self._total_receiving_amount = total_receiving_amount
        self._total_sending_amount = total_sending_amount
        self._multiplier = multiplier
        self._fees = fees

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionFx':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transaction_fx of this TransactionFx.  # noqa: E501
        :rtype: TransactionFx
        """
        return util.deserialize_model(dikt, cls)

    @property
    def receiving_currency(self) -> Currency:
        """Gets the receiving_currency of this TransactionFx.


        :return: The receiving_currency of this TransactionFx.
        :rtype: Currency
        """
        return self._receiving_currency

    @receiving_currency.setter
    def receiving_currency(self, receiving_currency: Currency):
        """Sets the receiving_currency of this TransactionFx.


        :param receiving_currency: The receiving_currency of this TransactionFx.
        :type receiving_currency: Currency
        """

        self._receiving_currency = receiving_currency

    @property
    def sending_currency(self) -> Currency:
        """Gets the sending_currency of this TransactionFx.


        :return: The sending_currency of this TransactionFx.
        :rtype: Currency
        """
        return self._sending_currency

    @sending_currency.setter
    def sending_currency(self, sending_currency: Currency):
        """Sets the sending_currency of this TransactionFx.


        :param sending_currency: The sending_currency of this TransactionFx.
        :type sending_currency: Currency
        """

        self._sending_currency = sending_currency

    @property
    def total_receiving_amount(self) -> int:
        """Gets the total_receiving_amount of this TransactionFx.

        The total amount that will be received in the smallest unit of the receiving currency (eg. cents).  # noqa: E501

        :return: The total_receiving_amount of this TransactionFx.
        :rtype: int
        """
        return self._total_receiving_amount

    @total_receiving_amount.setter
    def total_receiving_amount(self, total_receiving_amount: int):
        """Sets the total_receiving_amount of this TransactionFx.

        The total amount that will be received in the smallest unit of the receiving currency (eg. cents).  # noqa: E501

        :param total_receiving_amount: The total_receiving_amount of this TransactionFx.
        :type total_receiving_amount: int
        """
        if total_receiving_amount is not None and total_receiving_amount <= 0:  # noqa: E501
            raise ValueError("Invalid value for `total_receiving_amount`, must be a value greater than `0`")  # noqa: E501

        self._total_receiving_amount = total_receiving_amount

    @property
    def total_sending_amount(self) -> int:
        """Gets the total_sending_amount of this TransactionFx.

        The total amount that will be sent in the smallest unit of the sending currency (eg. cents).  # noqa: E501

        :return: The total_sending_amount of this TransactionFx.
        :rtype: int
        """
        return self._total_sending_amount

    @total_sending_amount.setter
    def total_sending_amount(self, total_sending_amount: int):
        """Sets the total_sending_amount of this TransactionFx.

        The total amount that will be sent in the smallest unit of the sending currency (eg. cents).  # noqa: E501

        :param total_sending_amount: The total_sending_amount of this TransactionFx.
        :type total_sending_amount: int
        """
        if total_sending_amount is not None and total_sending_amount <= 0:  # noqa: E501
            raise ValueError("Invalid value for `total_sending_amount`, must be a value greater than `0`")  # noqa: E501

        self._total_sending_amount = total_sending_amount

    @property
    def multiplier(self) -> float:
        """Gets the multiplier of this TransactionFx.

        Number of sending currency units per receiving currency unit.  # noqa: E501

        :return: The multiplier of this TransactionFx.
        :rtype: float
        """
        return self._multiplier

    @multiplier.setter
    def multiplier(self, multiplier: float):
        """Sets the multiplier of this TransactionFx.

        Number of sending currency units per receiving currency unit.  # noqa: E501

        :param multiplier: The multiplier of this TransactionFx.
        :type multiplier: float
        """
        if multiplier is not None and multiplier <= 0:  # noqa: E501
            raise ValueError("Invalid value for `multiplier`, must be a value greater than `0`")  # noqa: E501

        self._multiplier = multiplier

    @property
    def fees(self) -> int:
        """Gets the fees of this TransactionFx.

        The fees associated with the quote in the smallest unit of the sending currency (eg. cents).  # noqa: E501

        :return: The fees of this TransactionFx.
        :rtype: int
        """
        return self._fees

    @fees.setter
    def fees(self, fees: int):
        """Sets the fees of this TransactionFx.

        The fees associated with the quote in the smallest unit of the sending currency (eg. cents).  # noqa: E501

        :param fees: The fees of this TransactionFx.
        :type fees: int
        """
        if fees is not None and fees < 0:  # noqa: E501
            raise ValueError("Invalid value for `fees`, must be a value greater than or equal to `0`")  # noqa: E501

        self._fees = fees
