from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from umaauth.models.base_model import Model
from umaauth import util


class ExecuteQuoteRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payment_hash=None):  # noqa: E501
        """ExecuteQuoteRequest - a model defined in OpenAPI

        :param payment_hash: The payment_hash of this ExecuteQuoteRequest.  # noqa: E501
        :type payment_hash: str
        """
        self.openapi_types = {
            'payment_hash': str
        }

        self.attribute_map = {
            'payment_hash': 'payment_hash'
        }

        self._payment_hash = payment_hash

    @classmethod
    def from_dict(cls, dikt) -> 'ExecuteQuoteRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExecuteQuoteRequest of this ExecuteQuoteRequest.  # noqa: E501
        :rtype: ExecuteQuoteRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_hash(self) -> str:
        """Gets the payment_hash of this ExecuteQuoteRequest.

        The payment hash of the quote to execute.  # noqa: E501

        :return: The payment_hash of this ExecuteQuoteRequest.
        :rtype: str
        """
        return self._payment_hash

    @payment_hash.setter
    def payment_hash(self, payment_hash: str):
        """Sets the payment_hash of this ExecuteQuoteRequest.

        The payment hash of the quote to execute.  # noqa: E501

        :param payment_hash: The payment_hash of this ExecuteQuoteRequest.
        :type payment_hash: str
        """
        if payment_hash is None:
            raise ValueError("Invalid value for `payment_hash`, must not be `None`")  # noqa: E501

        self._payment_hash = payment_hash
