from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from umaauth.models.base_model import Model
from umaauth.models.currency_preference import CurrencyPreference
from umaauth import util

from umaauth.models.currency_preference import CurrencyPreference  # noqa: E501

class LookupUserResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, currencies=None):  # noqa: E501
        """LookupUserResponse - a model defined in OpenAPI

        :param currencies: The currencies of this LookupUserResponse.  # noqa: E501
        :type currencies: List[CurrencyPreference]
        """
        self.openapi_types = {
            'currencies': List[CurrencyPreference]
        }

        self.attribute_map = {
            'currencies': 'currencies'
        }

        self._currencies = currencies

    @classmethod
    def from_dict(cls, dikt) -> 'LookupUserResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LookupUserResponse of this LookupUserResponse.  # noqa: E501
        :rtype: LookupUserResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def currencies(self) -> List[CurrencyPreference]:
        """Gets the currencies of this LookupUserResponse.

        The currencies the receiver accepts in order of preference.  # noqa: E501

        :return: The currencies of this LookupUserResponse.
        :rtype: List[CurrencyPreference]
        """
        return self._currencies

    @currencies.setter
    def currencies(self, currencies: List[CurrencyPreference]):
        """Sets the currencies of this LookupUserResponse.

        The currencies the receiver accepts in order of preference.  # noqa: E501

        :param currencies: The currencies of this LookupUserResponse.
        :type currencies: List[CurrencyPreference]
        """

        self._currencies = currencies
