// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




// PayKeysendRequestTlvRecordsInner - The tlv record.
type PayKeysendRequestTlvRecordsInner struct {

	// The tlv type
	Type int32 `json:"type"`

	// The hex encoded tlv value.
	Value string `json:"value"`
}

// AssertPayKeysendRequestTlvRecordsInnerRequired checks if the required fields are not zero-ed
func AssertPayKeysendRequestTlvRecordsInnerRequired(obj PayKeysendRequestTlvRecordsInner) error {
	elements := map[string]interface{}{
		"type": obj.Type,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPayKeysendRequestTlvRecordsInnerConstraints checks if the values respects the defined constraints
func AssertPayKeysendRequestTlvRecordsInnerConstraints(obj PayKeysendRequestTlvRecordsInner) error {
	return nil
}
