// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type PayToAddressResponse struct {

	// The preimage of the payment.
	Preimage string `json:"preimage"`

	Quote Quote `json:"quote"`
}

// AssertPayToAddressResponseRequired checks if the required fields are not zero-ed
func AssertPayToAddressResponseRequired(obj PayToAddressResponse) error {
	elements := map[string]interface{}{
		"preimage": obj.Preimage,
		"quote": obj.Quote,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertQuoteRequired(obj.Quote); err != nil {
		return err
	}
	return nil
}

// AssertPayToAddressResponseConstraints checks if the values respects the defined constraints
func AssertPayToAddressResponseConstraints(obj PayToAddressResponse) error {
	if err := AssertQuoteConstraints(obj.Quote); err != nil {
		return err
	}
	return nil
}
