// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type PayInvoiceRequest struct {

	// The bolt11 invoice to pay.
	Invoice string `json:"invoice"`

	// The amount to pay for a 0-amount invoice.
	Amount *int64 `json:"amount,omitempty"`
}

// AssertPayInvoiceRequestRequired checks if the required fields are not zero-ed
func AssertPayInvoiceRequestRequired(obj PayInvoiceRequest) error {
	elements := map[string]interface{}{
		"invoice": obj.Invoice,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPayInvoiceRequestConstraints checks if the values respects the defined constraints
func AssertPayInvoiceRequestConstraints(obj PayInvoiceRequest) error {
	return nil
}
