// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type ExecuteQuoteResponse struct {

	// The preimage of the payment.
	Preimage string `json:"preimage"`
}

// AssertExecuteQuoteResponseRequired checks if the required fields are not zero-ed
func AssertExecuteQuoteResponseRequired(obj ExecuteQuoteResponse) error {
	elements := map[string]interface{}{
		"preimage": obj.Preimage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertExecuteQuoteResponseConstraints checks if the values respects the defined constraints
func AssertExecuteQuoteResponseConstraints(obj ExecuteQuoteResponse) error {
	return nil
}
