// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type ExecuteQuoteRequest struct {

	// The payment hash of the quote to execute.
	PaymentHash string `json:"payment_hash"`
}

// AssertExecuteQuoteRequestRequired checks if the required fields are not zero-ed
func AssertExecuteQuoteRequestRequired(obj ExecuteQuoteRequest) error {
	elements := map[string]interface{}{
		"payment_hash": obj.PaymentHash,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertExecuteQuoteRequestConstraints checks if the values respects the defined constraints
func AssertExecuteQuoteRequestConstraints(obj ExecuteQuoteRequest) error {
	return nil
}
