// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth


import (
	"errors"
)



type MakeInvoiceRequest struct {

	// The amount to invoice in msats.
	Amount int64 `json:"amount"`

	// A memo to attach to the invoice.
	Description string `json:"description,omitempty"`

	// A hash of a longer description field.
	DescriptionHash string `json:"description_hash,omitempty"`

	// The number of seconds until the invoice expires.
	Expiry int32 `json:"expiry,omitempty"`
}

// AssertMakeInvoiceRequestRequired checks if the required fields are not zero-ed
func AssertMakeInvoiceRequestRequired(obj MakeInvoiceRequest) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMakeInvoiceRequestConstraints checks if the values respects the defined constraints
func AssertMakeInvoiceRequestConstraints(obj MakeInvoiceRequest) error {
	if obj.Amount < 0 {
		return &ParsingError{Param: "Amount", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
