// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * UMA Auth API
 *
 * This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
 *
 * API version: 0.1
 */

package umaauth




type ExecuteQuoteRequest struct {

	// The code of the currency the sender used to set budget.  Optional if it is the same as `sending_currency_code`.
	BudgetCurrencyCode string `json:"budget_currency_code,omitempty"`
}

// AssertExecuteQuoteRequestRequired checks if the required fields are not zero-ed
func AssertExecuteQuoteRequestRequired(obj ExecuteQuoteRequest) error {
	return nil
}

// AssertExecuteQuoteRequestConstraints checks if the values respects the defined constraints
func AssertExecuteQuoteRequestConstraints(obj ExecuteQuoteRequest) error {
	return nil
}
