# coding: utf-8

"""
    UMA Auth API

    This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.

    The version of the OpenAPI document: 0.1
    Contact: info@lightspark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    The NIP47 response error code.
    """

    """
    allowed enum values
    """
    RATE_LIMITED = 'RATE_LIMITED'
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
    PAYMENT_FAILED = 'PAYMENT_FAILED'
    NOT_FOUND = 'NOT_FOUND'
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED'
    RESTRICTED = 'RESTRICTED'
    UNAUTHORIZED = 'UNAUTHORIZED'
    INTERNAL = 'INTERNAL'
    OTHER = 'OTHER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


