/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models


/**
* The NIP47 response error code.
* Values: RATE_LIMITED,NOT_IMPLEMENTED,INSUFFICIENT_BALANCE,PAYMENT_FAILED,NOT_FOUND,QUOTA_EXCEEDED,RESTRICTED,UNAUTHORIZED,INTERNAL,OTHER
*/
enum class ErrorCode(val value: kotlin.String) {

    RATE_LIMITED("RATE_LIMITED"),

    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),

    INSUFFICIENT_BALANCE("INSUFFICIENT_BALANCE"),

    PAYMENT_FAILED("PAYMENT_FAILED"),

    NOT_FOUND("NOT_FOUND"),

    QUOTA_EXCEEDED("QUOTA_EXCEEDED"),

    RESTRICTED("RESTRICTED"),

    UNAUTHORIZED("UNAUTHORIZED"),

    INTERNAL("INTERNAL"),

    OTHER("OTHER");

}

