/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models


/**
 * 
 * @param balance The balance of the user's wallet.
 * @param currencyCode The currency code of the balance. Assumed to be msats if not provided.
 */
data class GetBalanceResponse(
    /* The balance of the user's wallet. */
    val balance: java.math.BigDecimal,
    /* The currency code of the balance. Assumed to be msats if not provided. */
    val currencyCode: kotlin.String? = null
) 

