/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models


/**
 * 
 * @param paymentRequest The full, encoded payment request.
 * @param amount The amount of the invoice in msats.
 * @param paymentHash The payment hash of the invoice.
 * @param memo A memo attached to the invoice.
 * @param metadata Additional metadata attached to the invoice.
 * @param preimage The payment preimage of the invoice.
 * @param expiresAt The time the invoice expires.
 * @param createdAt The time the invoice was created.
 * @param settledAt The time the invoice was settled.
 * @param type Whether the invoice is incoming (created by this user) or outgoing (created by another user).
 */
data class Invoice(
    /* The full, encoded payment request. */
    val paymentRequest: kotlin.String? = null,
    /* The amount of the invoice in msats. */
    val amount: java.math.BigDecimal? = null,
    /* The payment hash of the invoice. */
    val paymentHash: kotlin.String? = null,
    /* A memo attached to the invoice. */
    val memo: kotlin.String? = null,
    /* Additional metadata attached to the invoice. */
    val metadata: kotlin.Any? = null,
    /* The payment preimage of the invoice. */
    val preimage: kotlin.String? = null,
    /* The time the invoice expires. */
    val expiresAt: java.time.OffsetDateTime? = null,
    /* The time the invoice was created. */
    val createdAt: java.time.OffsetDateTime? = null,
    /* The time the invoice was settled. */
    val settledAt: java.time.OffsetDateTime? = null,
    /* Whether the invoice is incoming (created by this user) or outgoing (created by another user). */
    val type: Invoice.Type? = null
) 
{
    /**
    * Whether the invoice is incoming (created by this user) or outgoing (created by another user).
    * Values: incoming,outgoing
    */
    enum class Type(val value: kotlin.String){
        incoming("incoming"),
        outgoing("outgoing");
    }
}

