/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models

import me.uma.auth.models.PayKeysendRequestTlvRecordsInner

/**
 * 
 * @param amount The amount to pay in msats.
 * @param pubkey The public key of the receiver's node.
 * @param preimage Preimage of the payment.
 * @param tlvRecords The tlv records.
 */
data class PayKeysendRequest(
    /* The amount to pay in msats. */
    val amount: kotlin.Long,
    /* The public key of the receiver's node. */
    val pubkey: kotlin.String,
    /* Preimage of the payment. */
    val preimage: kotlin.String? = null,
    /* The tlv records. */
    val tlvRecords: kotlin.collections.List<PayKeysendRequestTlvRecordsInner>? = null
) 

