/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models


/**
 * 
 * @param sendingCurrencyCode The currency code of the sender's balance.
 * @param receivingCurrencyCode The currency code of the receiver's balance.
 * @param paymentHash The payment hash of the quote. Used as an identifier to execute the quote.
 * @param expiresAt The time the quote expires.
 * @param multiplier Number of sending currency units per receiving currency unit.
 * @param fees The fees associated with the quote in the smallest unit of the sending currency (eg. cents).
 * @param totalSendingAmount The total amount that will be sent in the smallest unit of the sending currency (eg. cents).
 * @param totalReceivingAmount The total amount that will be received in the smallest unit of the receiving currency (eg. cents).
 * @param createdAt The time the quote was created.
 */
data class Quote(
    /* The currency code of the sender's balance. */
    val sendingCurrencyCode: kotlin.String,
    /* The currency code of the receiver's balance. */
    val receivingCurrencyCode: kotlin.String,
    /* The payment hash of the quote. Used as an identifier to execute the quote. */
    val paymentHash: kotlin.String,
    /* The time the quote expires. */
    val expiresAt: java.time.OffsetDateTime,
    /* Number of sending currency units per receiving currency unit. */
    val multiplier: kotlin.Int,
    /* The fees associated with the quote in the smallest unit of the sending currency (eg. cents). */
    val fees: kotlin.Int,
    /* The total amount that will be sent in the smallest unit of the sending currency (eg. cents). */
    val totalSendingAmount: kotlin.Int,
    /* The total amount that will be received in the smallest unit of the receiving currency (eg. cents). */
    val totalReceivingAmount: kotlin.Int,
    /* The time the quote was created. */
    val createdAt: java.time.OffsetDateTime
) 

