/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models

import me.uma.auth.models.Currency

/**
 * Foreign exchange rate for the transaction.
 * @param receivingCurrency 
 * @param sendingCurrency 
 * @param totalReceivingAmount The total amount that will be received in the smallest unit of the receiving currency (eg. cents).
 * @param totalSendingAmount The total amount that will be sent in the smallest unit of the sending currency (eg. cents).
 * @param multiplier Number of sending currency units per receiving currency unit.
 * @param fees The fees associated with the quote in the smallest unit of the sending currency (eg. cents).
 */
data class TransactionFx(
    val receivingCurrency: Currency? = null,
    val sendingCurrency: Currency? = null,
    /* The total amount that will be received in the smallest unit of the receiving currency (eg. cents). */
    val totalReceivingAmount: kotlin.Long? = null,
    /* The total amount that will be sent in the smallest unit of the sending currency (eg. cents). */
    val totalSendingAmount: kotlin.Long? = null,
    /* Number of sending currency units per receiving currency unit. */
    val multiplier: java.math.BigDecimal? = null,
    /* The fees associated with the quote in the smallest unit of the sending currency (eg. cents). */
    val fees: kotlin.Long? = null
) 

