/**
* UMA Auth API
* This API allows you to authenticate with the UMA server to take actions on a user's wallet. It's the exposed communication layer between the NWC server and the main UMA server.
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package me.uma.auth.models

import me.uma.auth.models.TransactionType

/**
 * 
 * @param type 
 * @param paymentHash Payment hash for the payment
 * @param amount Value in msats.
 * @param createdAt The time the payment/invoice was created.
 * @param invoice The full, encoded invoice.
 * @param description The invoice's description.
 * @param descriptionHash The invoice's description hash.
 * @param preimage The payment preimage, optional if unpaid.
 * @param feesPaid Value in msats.
 * @param expiresAt The time the invoice expires.
 * @param settledAt The time at which the transaction was settled, if it was settled.
 * @param metadata Additional metadata attached to the invoice.
 */
data class Transaction(
    val type: TransactionType,
    /* Payment hash for the payment */
    val paymentHash: kotlin.String,
    /* Value in msats. */
    val amount: kotlin.Long,
    /* The time the payment/invoice was created. */
    val createdAt: kotlin.Long,
    /* The full, encoded invoice. */
    val invoice: kotlin.String? = null,
    /* The invoice's description. */
    val description: kotlin.String? = null,
    /* The invoice's description hash. */
    val descriptionHash: kotlin.String? = null,
    /* The payment preimage, optional if unpaid. */
    val preimage: kotlin.String? = null,
    /* Value in msats. */
    val feesPaid: kotlin.Long? = null,
    /* The time the invoice expires. */
    val expiresAt: kotlin.Long? = null,
    /* The time at which the transaction was settled, if it was settled. */
    val settledAt: kotlin.Long? = null,
    /* Additional metadata attached to the invoice. */
    val metadata: kotlin.Any? = null
) 

