/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BudgetEstimateResponse
 */
export interface BudgetEstimateResponse {
    /**
     * The estimated cost of the payment in the smallest unit of  `budget_currency_code`. This amount will be used to calculate  the amount to hold from the budget for this connection while  the payment is in-flight. 
     * @type {number}
     * @memberof BudgetEstimateResponse
     */
    estimatedBudgetCurrencyAmount: number;
}

/**
 * Check if a given object implements the BudgetEstimateResponse interface.
 */
export function instanceOfBudgetEstimateResponse(value: object): value is BudgetEstimateResponse {
    if (!('estimatedBudgetCurrencyAmount' in value) || value['estimatedBudgetCurrencyAmount'] === undefined) return false;
    return true;
}

export function BudgetEstimateResponseFromJSON(json: any): BudgetEstimateResponse {
    return BudgetEstimateResponseFromJSONTyped(json, false);
}

export function BudgetEstimateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetEstimateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'estimatedBudgetCurrencyAmount': json['estimated_budget_currency_amount'],
    };
}

export function BudgetEstimateResponseToJSON(value?: BudgetEstimateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'estimated_budget_currency_amount': value['estimatedBudgetCurrencyAmount'],
    };
}

