/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The NIP47 response error code.
 * @export
 */
export const ErrorCode = {
    RateLimited: 'RATE_LIMITED',
    NotImplemented: 'NOT_IMPLEMENTED',
    InsufficientBalance: 'INSUFFICIENT_BALANCE',
    PaymentFailed: 'PAYMENT_FAILED',
    NotFound: 'NOT_FOUND',
    QuotaExceeded: 'QUOTA_EXCEEDED',
    Restricted: 'RESTRICTED',
    Unauthorized: 'UNAUTHORIZED',
    Internal: 'INTERNAL',
    Other: 'OTHER'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export function instanceOfErrorCode(value: any): boolean {
    for (const key in ErrorCode) {
        if (Object.prototype.hasOwnProperty.call(ErrorCode, key)) {
            if ((ErrorCode as Record<string, ErrorCode>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

