/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteQuoteRequest
 */
export interface ExecuteQuoteRequest {
    /**
     * The code of the currency the sender used to set budget.  Optional if it is the same as `sending_currency_code`.
     * @type {string}
     * @memberof ExecuteQuoteRequest
     */
    budgetCurrencyCode?: string;
}

/**
 * Check if a given object implements the ExecuteQuoteRequest interface.
 */
export function instanceOfExecuteQuoteRequest(value: object): value is ExecuteQuoteRequest {
    return true;
}

export function ExecuteQuoteRequestFromJSON(json: any): ExecuteQuoteRequest {
    return ExecuteQuoteRequestFromJSONTyped(json, false);
}

export function ExecuteQuoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteQuoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'budgetCurrencyCode': json['budget_currency_code'] == null ? undefined : json['budget_currency_code'],
    };
}

export function ExecuteQuoteRequestToJSON(value?: ExecuteQuoteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'budget_currency_code': value['budgetCurrencyCode'],
    };
}

