/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBalanceResponse
 */
export interface GetBalanceResponse {
    /**
     * The balance of the user's wallet.
     * @type {number}
     * @memberof GetBalanceResponse
     */
    balance: number;
    /**
     * The currency code of the balance. Assumed to be msats if not provided.
     * @type {string}
     * @memberof GetBalanceResponse
     */
    currencyCode?: string | null;
}

/**
 * Check if a given object implements the GetBalanceResponse interface.
 */
export function instanceOfGetBalanceResponse(value: object): value is GetBalanceResponse {
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function GetBalanceResponseFromJSON(json: any): GetBalanceResponse {
    return GetBalanceResponseFromJSONTyped(json, false);
}

export function GetBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBalanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
    };
}

export function GetBalanceResponseToJSON(value?: GetBalanceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'balance': value['balance'],
        'currency_code': value['currencyCode'],
    };
}

