/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MakeInvoiceRequest
 */
export interface MakeInvoiceRequest {
    /**
     * The amount to invoice in msats.
     * @type {number}
     * @memberof MakeInvoiceRequest
     */
    amount: number;
    /**
     * A memo to attach to the invoice.
     * @type {string}
     * @memberof MakeInvoiceRequest
     */
    description?: string;
    /**
     * A hash of a longer description field.
     * @type {string}
     * @memberof MakeInvoiceRequest
     */
    descriptionHash?: string;
    /**
     * The number of seconds until the invoice expires.
     * @type {number}
     * @memberof MakeInvoiceRequest
     */
    expiry?: number;
}

/**
 * Check if a given object implements the MakeInvoiceRequest interface.
 */
export function instanceOfMakeInvoiceRequest(value: object): value is MakeInvoiceRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function MakeInvoiceRequestFromJSON(json: any): MakeInvoiceRequest {
    return MakeInvoiceRequestFromJSONTyped(json, false);
}

export function MakeInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MakeInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHash': json['description_hash'] == null ? undefined : json['description_hash'],
        'expiry': json['expiry'] == null ? undefined : json['expiry'],
    };
}

export function MakeInvoiceRequestToJSON(value?: MakeInvoiceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'description': value['description'],
        'description_hash': value['descriptionHash'],
        'expiry': value['expiry'],
    };
}

