/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayInvoiceRequest
 */
export interface PayInvoiceRequest {
    /**
     * The bolt11 invoice to pay.
     * @type {string}
     * @memberof PayInvoiceRequest
     */
    invoice: string;
    /**
     * The amount to pay for a 0-amount invoice.
     * @type {number}
     * @memberof PayInvoiceRequest
     */
    amount?: number | null;
    /**
     * The code of the currency the sender used to set budget.  Optional if the budget is set in SAT.
     * @type {string}
     * @memberof PayInvoiceRequest
     */
    budgetCurrencyCode?: string;
}

/**
 * Check if a given object implements the PayInvoiceRequest interface.
 */
export function instanceOfPayInvoiceRequest(value: object): value is PayInvoiceRequest {
    if (!('invoice' in value) || value['invoice'] === undefined) return false;
    return true;
}

export function PayInvoiceRequestFromJSON(json: any): PayInvoiceRequest {
    return PayInvoiceRequestFromJSONTyped(json, false);
}

export function PayInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invoice': json['invoice'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'budgetCurrencyCode': json['budget_currency_code'] == null ? undefined : json['budget_currency_code'],
    };
}

export function PayInvoiceRequestToJSON(value?: PayInvoiceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoice': value['invoice'],
        'amount': value['amount'],
        'budget_currency_code': value['budgetCurrencyCode'],
    };
}

