/* tslint:disable */
/* eslint-disable */
/**
 * UMA Auth API
 * This API allows you to authenticate with the UMA server to take actions on a user\'s wallet. It\'s the exposed communication layer between the NWC server and the main UMA server.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@lightspark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
} from './Currency';

/**
 * Foreign exchange rate for the transaction.
 * @export
 * @interface TransactionFx
 */
export interface TransactionFx {
    /**
     * 
     * @type {Currency}
     * @memberof TransactionFx
     */
    receivingCurrency?: Currency;
    /**
     * 
     * @type {Currency}
     * @memberof TransactionFx
     */
    sendingCurrency?: Currency;
    /**
     * The total amount that will be received in the smallest unit of the receiving currency (eg. cents).
     * @type {number}
     * @memberof TransactionFx
     */
    totalReceivingAmount?: number;
    /**
     * The total amount that will be sent in the smallest unit of the sending currency (eg. cents).
     * @type {number}
     * @memberof TransactionFx
     */
    totalSendingAmount?: number;
    /**
     * Number of sending currency units per receiving currency unit.
     * @type {number}
     * @memberof TransactionFx
     */
    multiplier?: number;
    /**
     * The fees associated with the quote in the smallest unit of the sending currency (eg. cents).
     * @type {number}
     * @memberof TransactionFx
     */
    fees?: number;
}

/**
 * Check if a given object implements the TransactionFx interface.
 */
export function instanceOfTransactionFx(value: object): value is TransactionFx {
    return true;
}

export function TransactionFxFromJSON(json: any): TransactionFx {
    return TransactionFxFromJSONTyped(json, false);
}

export function TransactionFxFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionFx {
    if (json == null) {
        return json;
    }
    return {
        
        'receivingCurrency': json['receiving_currency'] == null ? undefined : CurrencyFromJSON(json['receiving_currency']),
        'sendingCurrency': json['sending_currency'] == null ? undefined : CurrencyFromJSON(json['sending_currency']),
        'totalReceivingAmount': json['total_receiving_amount'] == null ? undefined : json['total_receiving_amount'],
        'totalSendingAmount': json['total_sending_amount'] == null ? undefined : json['total_sending_amount'],
        'multiplier': json['multiplier'] == null ? undefined : json['multiplier'],
        'fees': json['fees'] == null ? undefined : json['fees'],
    };
}

export function TransactionFxToJSON(value?: TransactionFx | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'receiving_currency': CurrencyToJSON(value['receivingCurrency']),
        'sending_currency': CurrencyToJSON(value['sendingCurrency']),
        'total_receiving_amount': value['totalReceivingAmount'],
        'total_sending_amount': value['totalSendingAmount'],
        'multiplier': value['multiplier'],
        'fees': value['fees'],
    };
}

