name: "Release Python Models SDK"

on:
  release:
    types: ["released"]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'python-models-') }}
    environment:
      name: publish
      url: https://pypi.org/p/universal-money-address
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 10
      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          cache: "pipenv"
          cache-dependency-path: "codegen/python-models/Pipfile.lock"
      - name: "Install pipenv"
        working-directory: "codegen/python-models"
        run: "pip install pipenv wheel"
      - name: "Install dependencies"
        working-directory: "codegen/python-models"
        run: "rm -rf $(pipenv --venv) && pipenv install --dev"
      - name: "Build dist"
        working-directory: "codegen/python-models"
        run: "pipenv run python setup.py sdist --format=zip"
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: "codegen/python-models/dist"
